### ISSUE TITLE
Install via bower miss the css files

### ISSUE THREAD

**Issue by boogiebug** [Globegitter/chartist-plugin-tooltip#36] opened 2015-11-08 04:04 UTC
When I install the package via bower, I did not get the css files in dist folder. I guess that the list of css files are missing in the bower.json.

**Comment by eduardocasas** [comment] 2015-11-17 10:10
+1

**Comment by dominicrico** [comment] 2015-11-17 10:47
The thing is that @Globegitter has to release a new version. Bower installs always the latest release and in the v0.0.12 release are no css files included in the package.

**Comment by Globegitter** [comment] 2015-12-11 10:43
@boogiebug @eduardocasas @dominicrico Anyone of you wants write access to the repo to be able to release new versions?

**Comment by lookfirst** [comment] 2016-01-07 21:55
Let's do another release please!

**Comment by vool** [comment] 2016-01-11 22:13
hi @Globegitter,

Just came here to say highlight the same issues with the bower package. 
I am happy to do the release if you want to grant me write access to the repo.

Keith

**Comment by vool** [comment] 2016-01-11 22:25
Until a new version is released you can grab an up-to-date package via

bower install git@github.com:Globegitter/chartist-plugin-tooltip.git#master

**Comment by dominicrico** [comment] 2016-01-14 14:16
@Globegitter If you would grand me write access then I would do a new release.

**Comment by daN4cat** [comment] 2016-05-25 19:17
Yep, this should be fixed.

**Comment by daN4cat** [comment] 2016-05-25 19:19
And `bower install git@github.com:Globegitter/chartist-plugin-tooltip.git#master` does not work either. Any tip?

**Comment by Globegitter** [comment] 2016-05-26 08:58
@dominicrico you have access now :)

**Comment by daN4cat** [comment] 2016-05-26 10:19
A fix would be great indeed.

**Comment by ealves-pt** [comment] 2016-07-22 16:40
More or less a duplicate of #12.

Probably solved in the current release. Re-open the issue if the problem persists.

**Closed by ealves-pt** 2016-07-22 16:40 UTC
Labels: bug, duplicate
