### ISSUE TITLE
Display value in tooltip when value is 0

### ISSUE THREAD

**Issue by hanface** [Globegitter/chartist-plugin-tooltip#39] opened 2015-11-26 04:41 UTC
Tooltips don't display 0 values, is this was intentional? I have a line graph that I need tooltips to display 0 values, I was wondering if you had a solution I could use to display them?

**Comment by dominicrico** [comment] 2015-11-26 06:09
The thing is that 0 values have a height of 0px and we are not able to bind mouse events on something that is not clickable or something else.

**Comment by hanface** [comment] 2015-11-27 03:38
The tooltip still appears on hover, and it display's the $ in there, so it doesn't seem like a height problem to me. Here is a demo so you can see what I mean.

http://codepen.io/Han/pen/MaMXpw

**Comment by psalaets** [comment] 2016-01-23 06:48
I think this is being caused by gionkunz/chartist-js#464

**Comment by psalaets** [comment] 2016-03-29 17:42
Fixed in [Chartist 0.9.6](https://github.com/gionkunz/chartist-js/blob/develop/CHANGELOG.md#v096---22-feb-2016)

**Comment by ealves-pt** [comment] 2016-07-22 16:28
Seems to be fixed. Re-open this if the problem persists.

**Closed by ealves-pt** 2016-07-22 16:28 UTC
